### ISSUE TITLE
Incorrect latlong for several mrt stations in mrtsg.csv

### ISSUE THREAD

**Issue by claussian** [hxchua/datadoubleconfirm#1]
Outram Park PURPLE: (1.30838264, 103.888648) should be (1.27976454,103.839573)

Dakota: (1.28140498, 103.839125) should be (1.3083819726001047, 103.888662)

Ang Mo Kio: Duplicated rows

**Comment by hxchua** [comment]
Thanks for highlighting.

Updated on 20/06/2019:
Longitude and Latitude for Dakota MRT station and Outram Park MRT station (Purple line) corrected (somehow the pair was previously swopped).
Duplicate records of Ang Mo Kio MRT station also removed.
